// Font This file holds the logic for our automatic font subsetting and optimization behaviour.
//
// Drop a .ttf or .otf into /fonts and the build system will scan every page of the site, collect every character actually used, and emit a woff2 containing only those glyphs. Static and variable fonts both work, as do TrueType and CFF outlines.
//
// Leave /fonts empty and none of this happens — the feature costs you nothing until you decide to use it.

import { basename, copy, exec, extname, glob, mkdir, read, rm, write } from "./io.ts"
import { log, logIndented, yellow } from "./logging.ts"
import { unique } from "./util.ts"

// The file extensions we know how to subset.
const FONT_FORMATS = ["otf", "ttf"]

// Which OpenType features survive subsetting.
//
// Leave this blank to use hb-subset's own defaults. That's the recommended setting: it keeps the features text actually depends on — ligatures, contextual alternates, kerning, mark positioning, localised forms — and drops the rest.
//
// Be careful if you do set it. Passing a bare list *replaces* those defaults rather than adding to them, so asking for "kern" alone silently drops every ligature and stylistic set, which is a miserable bug to track down. Prefix a tag with + to add to the defaults instead (eg: "+ss01"). Use "*" to keep absolutely everything.
//
// Measured on Overpass, subset to the ~120 characters this starter happens to use:
//
//   (blank — hb-subset defaults)   41.5 kB    recommended
//   "kern"                         35.2 kB    -15%, but no ligatures or alternates
//   "*"                            53.2 kB    +28%, drags in alternate glyphs
//                                             that nothing on the site references
const LAYOUT_FEATURES = ""

// Variable fonts keep all of their axes by default, which is usually what you want — a single file covering every weight. To pin a fixed instance instead (smaller file, no variation), set this to something like "wght=400".
//
// Remember to match your @font-face to this choice: a variable font wants `format("woff2-variations")` and a `font-weight` range, a pinned one doesn't.
const INSTANCE = ""

let lastChars: string

export const generateFontSubsets = (text: string): boolean => {
  // Generated fonts and metadata are placed in the template folder
  const outPath = "content/static/fonts"
  const charFile = `${outPath}/chars.txt`

  // If there are no fonts to subset, there's nothing to do. That's the default state of a fresh copy of this build system, so we return quietly rather than warn.
  const sourceFiles = glob("fonts/**.*")
  if (!sourceFiles.some((file) => FONT_FORMATS.includes(extname(file)))) return true

  // Load the existing chars from the most recent compile (if any)
  try {
    lastChars ??= read(charFile)
  } catch {
    // The chars file was missing — that's good, it means we're regenerating from scratch.
  }

  // Get every unique char in every page, sorted, as a string
  const everyChar = Array.from(text)
  const newChars = unique(everyChar).sort().join("").toWellFormed()

  // If the set of chars has changed, we need to regenerate our font subsets
  if (newChars !== lastChars) {
    lastChars = newChars

    log("Regenerating Fonts")

    // Make sure we have the necessary binary dependencies. It's not a big deal if these are missing — see the README for more.
    try {
      exec("which -s hb-subset woff2_compress")
    } catch {
      logIndented(yellow("Binary deps missing — skipping font regeneration"))
      return false // signal failure
    }

    rm(outPath)
    mkdir(outPath)
    write(charFile, newChars)

    // Assemble the hb-subset flags once, from the constants at the top of this file
    const flags = [`--text-file="${charFile}"`]
    if (LAYOUT_FEATURES) flags.push(`--layout-features="${LAYOUT_FEATURES}"`)
    if (INSTANCE) flags.push(`--instance="${INSTANCE}"`)

    for (const file of sourceFiles) {
      const ext = extname(file)
      const base = basename(file)
      const dest = `${outPath}/${base}.${ext}`

      if (FONT_FORMATS.includes(ext)) {
        exec(`hb-subset "${file}" ${flags.join(" ")} -o "${dest}"`)
        exec(`woff2_compress ${dest}`)
        rm(dest) // Remove the subset (but non-woff) file
      } else if (base != "_README") {
        // Non-font files, like a License, just need to be copied straight across and then we're done. But we don't copy the _README, because we write a different readme down below.
        copy(file, dest)
        continue
      }
    }

    write(`${outPath}/_README.md`, "Hi! This folder is automatically deleted & regenerated by the build system. To add/remove fonts to the website, use the 'fonts' folder at the root of the repo.") // prettier-ignore
  }

  return true // signal success
}
